wdir: /home/eleve05/adaptnet
predict_dir: /home/eleve05/adaptnet/predict/
save_dir: home/eleve05/adaptnet/predict/
name: cad_500
save_folder: results
device: cuda:0
meshnet:
  checkpoint_path: home/eleve05/adaptnet/meshnet/logs/version_1/checkpoints/epoch=99-step=2400.ckpt
  input_channels: 7
  wdir: /home/eleve05/adaptnet/meshnet/
  data_dir: home/eleve05/adaptnet/meshnet/data/stokes/
  logs: home/eleve05/adaptnet/meshnet/logs/
  val_size: 0.15
  test_size: 0.1
  optimizer: torch.optim.AdamW
graphnet:
  checkpoint_path: home/eleve05/adaptnet/graphnet/logs/version_0/checkpoints/epoch=900-step=169388.ckpt
  dir: home/eleve05/adaptnet/
  wdir: /gpfs_new/home/eleve05/adaptnet/graphnet/
  data_dir: home/eleve05/adaptnet/graphnet/data/stokes/
  logs: home/eleve05/adaptnet/graphnet/logs/
  num_layers: 15
  input_dim_node: 7
  input_dim_edge: 3
  hidden_dim: 128
  output_dim: 2
  optimizer: torch.optim.AdamW