wdir: /home/eleve05/adaptnet
predict_dir: /home/eleve05/adaptnet/src/
save_dir: /home/eleve05/adaptnet/src/
name: 500
save_folder: results
device: cuda:0
meshnet:
  checkpoint_path: /home/eleve05/adaptnet/meshnet/logs/version_1/checkpoints/epoch=99-step=2400.ckpt
  wdir: /home/eleve05/adaptnet/meshnet/
  data_dir: /home/eleve05/adaptnet/meshnet/data/stokes2/
  logs: /home/eleve05/adaptnet/meshnet/logs/
  dim: 2
  num_layers: 15
  input_dim_node: 5
  input_dim_edge: 8
  hidden_dim: 128
  output_dim: 1
  optimizer: torch.optim.AdamW
graphnet:
  checkpoint_path: /home/eleve05/adaptnet/graphnet/logs/version_8/checkpoints/epoch=999-step=188000.ckpt
  dir: /home/eleve05/adaptnet/
  wdir: /home/eleve05/adaptnet/graphnet/
  data_dir: /home/eleve05/adaptnet/graphnet/data/stokes2/
  logs: /home/eleve05/adaptnet/graphnet/logs/
  dim: 2
  num_layers: 15
  input_dim_node: 7
  input_dim_edge: 3
  hidden_dim: 128
  output_dim: 2
  optimizer: torch.optim.AdamW