wdir: /home/eleve05/adaptnet # TODO: change this to your adaptnet directory
predict_dir: /home/eleve05/adaptnet/src/ # TODO: change this accordingly
save_dir: /home/eleve05/adaptnet/src/ # TODO: change this accordingly
name: 500 # TODO: change this to the name of your experiment
save_folder: results
device: cuda:0
meshnet:
  checkpoint_path: /home/eleve05/adaptnet/meshnet/logs/version_4/checkpoints/epoch=999-step=188000.ckpt # TODO: change this to the path of your meshnet checkpoint
  wdir: /home/eleve05/adaptnet/meshnet/ # TODO: change this to your meshnet directory
  data_dir: /home/eleve05/adaptnet/meshnet/data/stokes3/ # TODO: change this to your meshnet data directory
  logs: /home/eleve05/adaptnet/meshnet/logs/ # TODO: change this to your meshnet logs directory
  dim: 3
  num_layers: 15
  input_dim_node: 5
  input_dim_edge: 8
  hidden_dim: 128
  output_dim: 1
  optimizer: torch.optim.AdamW
graphnet:
  checkpoint_path: /home/eleve05/adaptnet/graphnet/logs/version_12/checkpoints/epoch=4999-step=940000.ckpt # TODO: change this to the path of your graphnet checkpoint
  dir: /home/eleve05/adaptnet/ # TODO: change this to your adaptnet directory
  wdir: /home/eleve05/adaptnet/graphnet/ # TODO: change this to your graphnet directory
  data_dir: /home/eleve05/adaptnet/graphnet/data/stokes3/ # TODO: change this to your graphnet data directory
  logs: /home/eleve05/adaptnet/graphnet/logs/ # TODO: change this to your graphnet logs directory
  dim: 3
  num_layers: 15
  hidden_dim: 128
  optimizer: torch.optim.AdamW
  u_0: 1.0
  v_0: 0.0
  w_0: 0.0