wdir: /home/upelissier/30-Code/
predict_dir: /home/upelissier/30-Code/src/
save_dir: /data/users/upelissier/30-Code/src/
name: stokes_500
save_folder: results
device: cuda:0
meshnet:
  checkpoint_path: /data/users/upelissier/30-Code/meshnet/logs/version_0/checkpoints/epoch=99-step=1000.ckpt
  input_channels: 7
  wdir: /home/upelissier/30-Code/meshnet/
  data_dir: /data/users/upelissier/30-Code/meshnet/data/stokes/
  logs: /data/users/upelissier/30-Code/meshnet/logs/
  val_size: 0.15
  test_size: 0.1
  optimizer: torch.optim.AdamW
graphnet:
  checkpoint_path: /data/users/upelissier/30-Code/graphnet/logs/version_0/checkpoints/epoch=900-step=169388.ckpt
  dir: /data/users/upelissier/30-Code/
  wdir: /gpfs_new/home/upelissier/30-Code/graphnet/
  data_dir: /data/users/upelissier/30-Code/graphnet/data/stokes/
  logs: /data/users/upelissier/30-Code/graphnet/logs/
  num_layers: 15
  input_dim_node: 7
  input_dim_edge: 3
  hidden_dim: 128
  output_dim: 2
  optimizer: torch.optim.AdamW